### ISSUE TITLE
How to run the model?

### ISSUE THREAD

**Issue by naveenv2** [Speech-AI/SpeechX#1]
Hi!

Thanks for the great work! Could you please provide instructions to run the model inference on audio files?

Also, details regarding the audio input (file encoding, sample rate, etc) would be very useful.

Thanks!

**Comment by deciding** [comment]
Hi @naveenv2 , thanks for the question. 

The running script is in `asteroid/egs/librimix/TransMask/run.sh` we use wav files, the sampling rate is 8000. the more specs can be found in that file.

Sorry I am busy on other project recently. But feel free to ask me if there's any problem.

**Comment by naveenv2** [comment]
Thank you. Closing the issue for now.
